### ISSUE TITLE
PlayerStats not working on Folia

### ISSUE THREAD

**Issue by Duce008** [xGinko/BetterWorldStats#9]
I set up a test server with Folia, no other plugins exept BetterWorldStats.
![image](https://github.com/xGinko/BetterWorldStats/assets/119748024/e6c4d82e-37aa-4fd5-8bf5-9b44596922c9)

**Comment by xGinko** [comment]
Fixed in latest modrinth release. Seems I forgot to make one here but the fix is in:

https://modrinth.com/plugin/betterworldstats/version/1.10.1

**Comment by Duce008** [comment]
idk what im doing wrong im on newest version 1.10.1 i downloaded it from modrinth but it still doesnt work
![image](https://github.com/xGinko/BetterWorldStats/assets/119748024/c4d45c07-c838-4ccd-a210-97866a488366)

**Comment by xGinko** [comment]
Ah, I see what happened here. Looks like IntelliJ decided to rename my placeholders when I renamed one of the classes. The placeholder is %players%.

**Comment by xGinko** [comment]
@Duce008 If you just set it up, download 1.10.2 and reset your lang folder. Should be fixed now
